# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Package Test and Coverage (on Ubuntu)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # on demand

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Install system libraries
      run: |
        sudo apt-get install -y libgmp3-dev
        sudo apt-get install -y libmpfr-dev
        sudo apt-get install -y libmpc-dev

    - name: Install pip dependencies
      run: |

        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements.txt
        pip install -r requirements_optional.txt
        python -m pip install flake8 pytest
        pip install pytest pytest-cov
        pip install coveralls

    - name: Install conda dependencies
      run: |
        conda install pip

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest --cov-config=.coveragerc --cov=./ --cov-report=xml

    - name: codecov
      uses: codecov/codecov-action@v1